name: prod deployment

on:
    workflow_call:
    
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name : login to the server
              uses: appleboy/ssh-action@v1.2.5
              with: 
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                script: |
                 echo "starting deployment" 
                 mkdir -p devops

            - name: copy docker compose
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                source: "docker-compose.yml"
                target: ~/devops

            - name : login to the server and run the app
              uses: appleboy/ssh-action@v1.2.5
              with: 
                host: ${{ secrets.SERVER_IP }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                script: |
                 echo "running the deployment" 
                 sudo apt-get update  
                 sudo apt-get install docker.io -y
                 sudo apt-get install -y docker-compose-plugin
                 sudo usermod -aG $USER && newgrp docker
                 cd ~/devops
                 export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                 export DOCKER_TAG=${{ github.sha }}
                 echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
                 docker-compose down
                 docker-compose up -d --force-recreate



