name : trivy docker image scanning 

on:
    workflow_call

jobs:
    trivy-image-scanning:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: login to docker hub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.33.1
              with: 
                image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HARD,MEDIUM'

